### ISSUE TITLE
Organizing the Repository 

### ISSUE THREAD

**Issue by garg-madhur-garg** [garg-madhur-garg/python_projects#3]
Can anyone check which **programs are working** and which are not and also **organize the files** in a suitable manner

_**(Dedicated to Python Lovers)**_

**Comment by NgoQuocBao1010** [comment]
Hi, I believe I can help with this project! Can you assign me to this issue?

**Comment by garg-madhur-garg** [comment]
Issue assigned @NgoQuocBao1010

**Comment by garg-madhur-garg** [comment]
Issue fix #3

**Comment by garg-madhur-garg** [comment]
Fix #3
